# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               The General's Journey
tagline:             'A strength training journal'
description:         'My personal strength training diary containing all my successes, failures and everything in between.'
url:                 https://mbchoa.github.io/discipline
baseurl:             /discipline/
paginate:            5

# About/contact
author:
  name:              Michael-Bryant Choa
  url:               https://github.com/mbchoa
  email:             mbchoa@gmail.com

# Custom vars
version:             1.0.0
